"""FModels

Revision ID: 84e23ed678e8
Revises: a5178b6d4896
Create Date: 2023-09-24 22:57:45.098399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e23ed678e8'
down_revision: Union[str, None] = 'a5178b6d4896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_user', 'user_turn')
    op.add_column('games', sa.Column('turn_user_id', sa.BigInteger(), nullable=True))
    op.alter_column('games', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('games', 'turn_user_id')
    op.add_column('game_user', sa.Column('user_turn', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
