"""FinalModels

Revision ID: c4c6b5d1ced2
Revises: 4c51143aa860
Create Date: 2023-09-22 16:00:28.847936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c6b5d1ced2'
down_revision: Union[str, None] = '4c51143aa860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('question_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'games', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'question_id')
    # ### end Alembic commands ###
