"""FS Mig

Revision ID: e1360be64d9f
Revises: 
Create Date: 2023-09-19 14:06:36.930325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1360be64d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('game_user',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_vk_id'], ['users.vk_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_vk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_user')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
