"""Release

Revision ID: e9e89175f5a6
Revises: 4ea6a648738a
Create Date: 2023-10-02 16:21:41.997321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e89175f5a6'
down_revision: Union[str, None] = '4ea6a648738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status_last_action', sa.String(), nullable=True))
    op.drop_column('games', 'last_action')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('last_action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'status_last_action')
    # ### end Alembic commands ###
