"""ProbablyFinal

Revision ID: ec3d6f621bf9
Revises: 84e23ed678e8
Create Date: 2023-09-28 21:34:15.469048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3d6f621bf9'
down_revision: Union[str, None] = '84e23ed678e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('letters_revealed', sa.String(), nullable=True))
    op.add_column('games', sa.Column('last_action', sa.String(), nullable=True))
    op.add_column('users', sa.Column('total_points', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_points')
    op.drop_column('games', 'last_action')
    op.drop_column('games', 'letters_revealed')
    # ### end Alembic commands ###
